### ISSUE TITLE
Tutorial link is broken

### ISSUE THREAD

**Issue by theozhirsch** [wwylab/DeMixSC#1]
Hi, the link for the Tutorial https://github.com/wwylab/DeMixSC/blob/main/link leads to 404 - page not found. Could you please upload the Tutorial again?

**Comment by Sphingosine** [comment]
Hi, thank you for your interest in our method. The tutorial will be available this week. Please stay tuned and thank you for your patience!

**Comment by Sphingosine** [comment]
Hi, I am happy to inform you that the tutorial link is now live, and you can access it via this URL: https://sphingosine.github.io/tutorial/DeMixSC.html.
